services:
  librespeed:
    image: linuxserver/librespeed:latest
    container_name: librespeed
    hostname: librespeed
    restart: always
    networks:
      macvlan:
        ipv4_address: ${ipv4}
        ipv6_address: ${ipv6}
        mac_address: ${macaddress}


networks:
  macvlan:
    external: true
    name: ${MACVLAN_NET}